#!python
# genome_browser_links
# Takes a gene id and clicks through _View Gene in Genome Browser_ webpage to jbrowser'
# This module is necessary because a link is generated by clicking this button with an gene id extension I 
# can't figure out how to construct from the data given. So, the link on this page just has to be clicked. :P 

import time
from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
import json, requests, sys, pprint

def gb_link(geneid, browser): 
	'''Takes a gene id and clicks through _View Gene in Genome Browser_ webpage to jbrowser.'''
	# Input: genid(string)
	# Output: url (string)

	print('using gb_link')

	#Maybe the url isn't being constructed correctly? 
	
	url = 'https://research.nhgri.nih.gov/hydra/genewiki/gene_page.cgi?gene=' + geneid
	print ('open browser')
	browser.get(url)
	time.sleep(1)

	#Click the 'View Gene in Genome Browser link' - it seems to be the only way to get the correct json file
	try:
		link_to_genome = browser.find_element_by_link_text('View Gene in Genome Browser').click()
		print ('Found View_gene_elem with that xpath')
	except:
		print('Was not able to find View_gene_elem')
	
	# After clicking the button, store the window handle variable of second page.
	view_in_browser_page = browser.window_handles[0]
	jbrowser_page = browser.window_handles[1] 
	browser.switch_to.window(jbrowser_page)

	# This is crucial!!! If the browser does not have time to load the second page, 
	# the handle will not be reset to the correct page. Sleep time may need to be lengthened if browser takes too long to load
	# This may be a good thing to put in a try except to retry finding the link if it is not found immediately. 
	
	loading_time = 1

	while True:
		time.sleep(loading_time)
		print('*', end =" ")
		try: 
			test_page_loaded = browser.find_element_by_xpath(
			'//div[2]/div[4]/div[5]/div[2]/div/div/label[2]/input')
			break
		except:
			loading_time +=1

	try:
		JulianoCheckbox = browser.find_element_by_xpath(
		'//div[2]/div[4]/div[5]/div[2]/div/div/label[2]/input').click()
		print ('Found JulianoCheckbox')	
	except:
		print('Was not able to find JulianoCheckbox')
		print('May need to increase time.sleep to allow browser to load completely')
 
	browser.refresh()

	short_geneid = geneid.split('.')
	jbrowse_url = 'https://research.nhgri.nih.gov/hydra/jbrowse/data/tracks/aepLRv2_splign/'\
				  + short_geneid[0] + '/trackData.json'

	time.sleep(1)
	print ('close browser window')
	browser.close()
	browser.switch_to.window(view_in_browser_page)

	return jbrowse_url



