# !python
# json file transcript stripper module

import json, requests, sys, pprint
from selenium import webdriver
from selenium.webdriver.firefox.options import Options as FirefoxOptions
import urllib.request, urllib
import re

def transcripts_data(url, browser): 
	'''Download the JSON data as a file from the JSON browser
	# using a url generated by clicking a button in the genome browser
	# Then get the transcripts from the JSON browser data file.''' 
	# Input: url(string) 
	# Output: transcripts(list)
	
	print('using  json_stripper \n')

	transcripts =[0]
	response = requests.get(url)
	response.raise_for_status() # raise_for_status lets you know if the file downloaded sucessfully

	# Load JSON data into a Python variable.
	transcripts_data = json.loads(response.text)
	transcripts_text_file = transcripts_data['intervals']
	
	#regex expression
	pattern = re.compile('t\d+aep')
	transcripts = set(pattern.findall(response.text))

	return transcripts


	
	

 

